/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as NutritionSafetyRouteImport } from './routes/nutrition-safety'
import { Route as FeedingGuideRouteImport } from './routes/feeding-guide'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionSafetyRoute = NutritionSafetyRouteImport.update({
  id: '/nutrition-safety',
  path: '/nutrition-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingGuideRoute = FeedingGuideRouteImport.update({
  id: '/feeding-guide',
  path: '/feeding-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feeding-guide': typeof FeedingGuideRoute
  '/nutrition-safety': typeof NutritionSafetyRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feeding-guide': typeof FeedingGuideRoute
  '/nutrition-safety': typeof NutritionSafetyRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feeding-guide': typeof FeedingGuideRoute
  '/nutrition-safety': typeof NutritionSafetyRoute
  '/shop': typeof ShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/feeding-guide' | '/nutrition-safety' | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/feeding-guide' | '/nutrition-safety' | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/feeding-guide'
    | '/nutrition-safety'
    | '/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeedingGuideRoute: typeof FeedingGuideRoute
  NutritionSafetyRoute: typeof NutritionSafetyRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition-safety': {
      id: '/nutrition-safety'
      path: '/nutrition-safety'
      fullPath: '/nutrition-safety'
      preLoaderRoute: typeof NutritionSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding-guide': {
      id: '/feeding-guide'
      path: '/feeding-guide'
      fullPath: '/feeding-guide'
      preLoaderRoute: typeof FeedingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeedingGuideRoute: FeedingGuideRoute,
  NutritionSafetyRoute: NutritionSafetyRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
